// Production UI with fully intercepted APIs. No database writes or model calls.
const { chromium, expect } = require('@playwright/test')
const fs = require('node:fs')
const path = require('node:path')
const base = process.env.LIGHTSQL_UI_URL || 'http://127.0.0.1:8000'
const output = path.resolve(__dirname, '../../.local/design-review')
const source = { id: 'source', name: '销售业务库', database_type: 'postgresql', database: 'sales', enabled: true, status: 'connected', revision: 1, host: 'localhost', port: 5432, username: 'reader', tls_mode: 'prefer', description: '订单与客户数据', created_at: '2026-09-08T01:00:00Z' }
const topic = { id: 'sales', name: '销售经营', description: '从订单、客户到销售趋势，了解每一笔收入的来源。', availability: 'ready', metric_count: 3, dimension_count: 4, current_version: 2, source_name: source.name }
const conversation = { id: 'conversation', topic_id: topic.id, revision: 1, turns: [], created_at: '2026-09-08T02:00:00Z', expires_at: '2026-09-09T02:00:00Z' }

async function main() {
  fs.mkdirSync(output, { recursive: true })
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: 'zh-CN' })
  const page = await context.newPage()
  const errors = [], mutations = [], checks = []
  let topicMode = 'normal', deleteFails = true, topicDelay = 0
  let sources = [source], topics = [topic, { ...topic, id: 'inventory', name: '库存分析', availability: 'draft' }, { ...topic, id: 'customers', name: '客户增长', availability: 'needs_review' }]
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/api/v1/**', async route => {
    const req = route.request(), endpoint = new URL(req.url()).pathname.replace('/api/v1', ''), method = req.method()
    const respond = (json, status = 200) => route.fulfill({ status, json })
    if (method !== 'GET') mutations.push({ endpoint, method })
    if (endpoint === '/login/access-token') return respond({ access_token: 'fixture', token_type: 'bearer' })
    if (endpoint === '/users/me') return respond({ id: 'user', email: 'review@example.com', full_name: '数据管理员', is_superuser: true, is_active: true })
    if (endpoint === '/topics/') {
      if (method === 'POST') return respond({ detail: '主题名称已存在，请使用其他名称' }, 409)
      if (topicDelay) await new Promise(resolve => setTimeout(resolve, topicDelay))
      return topicMode === 'error' ? respond({ detail: '主题服务暂不可用' }, 503) : respond(topicMode === 'empty' ? [] : topics)
    }
    if (endpoint === '/datasources/') return respond({ data: sources, count: sources.length })
    if (endpoint === '/assistant/status') return respond({ configured: true, name: '企业分析模型', model: '内部配置' })
    if (endpoint === '/assistant/conversations') return respond(method === 'POST' ? conversation : [])
    if (endpoint === '/assistant/conversations/conversation') {
      if (method === 'DELETE') return deleteFails ? respond({ detail: '删除失败，请重试' }, 503) : respond({ success: true })
      return respond(conversation)
    }
    if (endpoint.endsWith('/events')) return route.fulfill({ status: 200, contentType: 'text/event-stream', body: ': connected\n\n' })
    if (endpoint === '/queries/topics/sales/catalog') return respond({ metrics: [], dimensions: [], filters: [], entities: [] })
    if (endpoint === '/assistant/topics/sales/tables') return respond([])
    if (endpoint.includes('/catalog/')) return respond([])
    errors.push(`Unexpected API ${method} ${endpoint}`)
    return respond([])
  })
  const shot = name => page.screenshot({ path: path.join(output, `${name}.png`), fullPage: true, animations: 'disabled' })
  const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  try {
    await page.goto(base + '/login')
    await page.getByRole('button', { name: '登录工作空间' }).click()
    await expect(page.getByText('请输入有效邮箱')).toBeVisible()
    expect(mutations).toHaveLength(0)
    await page.getByLabel('邮箱', { exact: true }).fill('review@example.com')
    await page.getByTestId('password-input').fill('fixture-password')
    await page.getByRole('button', { name: '显示密码', exact: true }).click()
    await expect(page.getByTestId('password-input')).toHaveAttribute('type', 'text')
    await page.getByRole('button', { name: '隐藏密码', exact: true }).click()
    await shot('login-desktop')
    await page.setViewportSize({ width: 390, height: 844 })
    await noOverflow()
    await shot('login-mobile')
    await page.getByRole('button', { name: '登录工作空间' }).click()
    await expect(page).toHaveURL(/topics/)
    checks.push('Login validation, password reveal, successful login, narrow viewport')

    await page.setViewportSize({ width: 1440, height: 1000 })
    await expect(page.locator('article')).toHaveCount(3)
    await shot('topics-desktop')
    await page.getByLabel('搜索主题', { exact: true }).fill('不存在')
    await expect(page.getByText('没有匹配的主题')).toBeVisible()
    await page.getByRole('button', { name: '清除搜索主题', exact: true }).click()
    await expect(page.getByLabel('搜索主题', { exact: true })).toBeFocused()
    await expect(page.locator('article')).toHaveCount(3)
    await page.getByRole('button', { name: '新建主题', exact: true }).click()
    await page.getByRole('button', { name: '创建并选择数据表' }).click()
    await expect(page.getByText('请填写主题名称', { exact: true })).toBeVisible()
    await expect(page.getByLabel('主题名称', { exact: true })).toBeFocused()
    await expect(page.getByLabel('主题名称', { exact: true })).toHaveAttribute('aria-invalid', 'true')
    await page.getByLabel('主题名称', { exact: true }).fill('销售经营')
    await page.getByRole('button', { name: '创建并选择数据表' }).click()
    await expect(page.getByRole('dialog').getByText('主题名称已存在，请使用其他名称')).toBeVisible()
    await expect(page.getByLabel('主题名称', { exact: true })).toHaveValue('销售经营')
    await page.keyboard.press('Escape')
    await expect(page.getByRole('button', { name: '新建主题', exact: true })).toBeFocused()
    checks.push('Search clear/focus, topic validation, conflict retention, dialog focus restoration')

    topics = Array.from({ length: 15 }, (_, i) => ({ ...topic, id: `t${i}`, name: `分析主题 ${i + 1}` }))
    await page.reload()
    await expect(page.locator('article')).toHaveCount(12)
    await page.getByRole('button', { name: /加载更多主题/ }).click()
    await expect(page.locator('article')).toHaveCount(15)
    topics = [topic]
    topicMode = 'empty'
    await page.reload()
    await expect(page.getByRole('heading', { name: '创建第一个业务主题' })).toBeVisible()
    topicMode = 'error'
    await page.reload()
    await expect(page.getByText('主题服务暂不可用')).toBeVisible({ timeout: 15000 })
    topicMode = 'normal'
    await page.getByRole('button', { name: '重试', exact: true }).click()
    await expect(page.locator('article')).toHaveCount(1)
    topicDelay = 1600
    await page.reload({ waitUntil: 'domcontentloaded' })
    await expect(page.getByRole('status').filter({ hasText: '正在加载业务主题' })).toBeVisible()
    await expect(page.locator('article')).toHaveCount(1)
    topicDelay = 0
    checks.push('Incremental display, empty, error/retry and delayed loading states')

    sources = Array.from({ length: 13 }, (_, i) => ({ ...source, id: `s${i}`, name: `业务数据库 ${i + 1}` }))
    await page.goto(base + '/datasources')
    await expect(page.locator('tbody tr')).toHaveCount(10)
    await page.getByRole('button', { name: '下一页', exact: true }).click()
    await expect(page.locator('tbody tr')).toHaveCount(3)
    await page.getByLabel('搜索数据源', { exact: true }).fill('数据库 13')
    await expect(page.locator('tbody tr')).toHaveCount(1)
    await page.getByRole('button', { name: '清除搜索数据源' }).click()
    await expect(page.locator('tbody tr')).toHaveCount(10)
    await page.getByRole('button', { name: '添加数据源', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: /保存/ }).click()
    await expect(page.getByLabel('显示名称', { exact: true })).toBeFocused()
    await expect(page.getByLabel('显示名称', { exact: true })).toHaveAttribute('aria-invalid', 'true')
    await page.getByLabel('显示名称', { exact: true }).fill('测试连接')
    await expect(page.getByLabel('显示名称', { exact: true })).not.toHaveAttribute('aria-invalid', 'true')
    await page.setViewportSize({ width: 390, height: 844 })
    await noOverflow()
    await shot('source-validation-mobile')
    await page.keyboard.press('Escape')
    await page.setViewportSize({ width: 1440, height: 1000 })
    await shot('datasources-desktop')
    checks.push('Datasource paging/reset, shared domain validation, inline ARIA errors, mobile dialog')

    await page.goto(base + '/ask?topic=sales')
    await expect(page.getByRole('heading', { name: '今天想了解什么？' })).toBeVisible()
    await page.getByLabel('业务主题', { exact: true }).focus()
    await page.keyboard.press('Space')
    await page.keyboard.press('Escape')
    await expect(page.getByLabel('业务主题', { exact: true })).toHaveValue('sales')
    await shot('ask-desktop')
    await page.getByRole('button', { name: '开始新会话' }).click()
    await expect(page.getByLabel('你的业务问题', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: '删除会话', exact: true }).click()
    const dialog = page.getByRole('dialog')
    await expect(dialog.getByRole('button', { name: '取消', exact: true })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('button', { name: '删除会话', exact: true })).toBeFocused()
    expect(mutations.filter(m => m.method === 'DELETE')).toHaveLength(0)
    await page.getByRole('button', { name: '删除会话', exact: true }).click()
    await dialog.getByRole('button', { name: '删除会话', exact: true }).click()
    await expect(dialog.getByText('删除失败，请重试')).toBeVisible()
    deleteFails = false
    await dialog.getByRole('button', { name: '删除会话', exact: true }).click()
    await expect(page.getByRole('heading', { name: '今天想了解什么？' })).toBeVisible()
    checks.push('Native scope select, new conversation, delete cancellation, failed delete/retry and focus')

    await page.goto(base + '/topics')
    await page.getByTestId('theme-button').click()
    await page.getByTestId('dark-mode').click()
    await page.setViewportSize({ width: 390, height: 844 })
    await noOverflow()
    await shot('topics-dark-mobile')
    await page.getByRole('button', { name: /打开导航栏|收起导航栏/ }).click()
    await expect(page.getByRole('dialog', { name: '工作空间导航' })).toBeVisible()
    await page.getByRole('link', { name: '数据库连接', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await noOverflow()
    await page.emulateMedia({ reducedMotion: 'reduce' })
    expect(await page.evaluate(() => getComputedStyle(document.querySelector('button')).transitionDuration)).toBe('1e-05s')
    expect(await page.evaluate(() => getComputedStyle(document.documentElement).scrollbarColor)).not.toBe('auto')
    await page.emulateMedia({ forcedColors: 'active' })
    expect(await page.evaluate(() => getComputedStyle(document.documentElement).scrollbarColor)).toBe('auto')
    checks.push('Dark theme, mobile navigation, reduced motion, global and forced-color scrollbars')
    expect(errors).toEqual([])
    fs.writeFileSync(path.join(output, 'results.json'), JSON.stringify({ passed: true, checks, errors, interceptedMutations: mutations }, null, 2))
    console.log(`PASS: ${checks.length} design/interaction groups; no live API writes or model calls.`)
  } catch (error) {
    await shot('failure')
    throw error
  } finally { await browser.close() }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
