"""add model gateways and assistant conversations

Revision ID: 22c020366c86
Revises: e4b106041004
Create Date: 2026-09-07 08:14:37.730072

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '22c020366c86'
down_revision = 'e4b106041004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistantturn',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('input_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('encrypted_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('gateway_id', sa.Uuid(), nullable=True),
    sa.Column('gateway_revision', sa.Integer(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('query_job_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'request_id')
    )
    op.create_index(op.f('ix_assistantturn_conversation_id'), 'assistantturn', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_assistantturn_status'), 'assistantturn', ['status'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('policy_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_actor_id'), 'conversation', ['actor_id'], unique=False)
    op.create_index(op.f('ix_conversation_topic_id'), 'conversation', ['topic_id'], unique=False)
    op.create_table('gatewayaudit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('gateway_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gatewaystate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelgateway',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('encrypted_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('json_mode', sa.Boolean(), nullable=False),
    sa.Column('thinking', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modelgateway')
    op.drop_table('gatewaystate')
    op.drop_table('gatewayaudit')
    op.drop_index(op.f('ix_conversation_topic_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_actor_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_assistantturn_status'), table_name='assistantturn')
    op.drop_index(op.f('ix_assistantturn_conversation_id'), table_name='assistantturn')
    op.drop_table('assistantturn')
    # ### end Alembic commands ###
