"""add external integration and embed sessions

Revision ID: 50620ca515f5
Revises: 5852f374df91
Create Date: 2026-09-07 17:40:47.053399

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '50620ca515f5'
down_revision = '5852f374df91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assertionuse',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embedsession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedsession_identity_id'), 'embedsession', ['identity_id'], unique=False)
    op.create_table('embedticket',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('challenge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrationaudit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrationaudit_action'), 'integrationaudit', ['action'], unique=False)
    op.create_index(op.f('ix_integrationaudit_client_id'), 'integrationaudit', ['client_id'], unique=False)
    op.create_table('integrationclient',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ceiling_user_id', sa.Uuid(), nullable=False),
    sa.Column('secret_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrationidentity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'subject')
    )
    op.create_index(op.f('ix_integrationidentity_actor_id'), 'integrationidentity', ['actor_id'], unique=True)
    op.create_index(op.f('ix_integrationidentity_client_id'), 'integrationidentity', ['client_id'], unique=False)
    op.create_table('integrationtask',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('policy_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('turn_id', sa.Uuid(), nullable=True),
    sa.Column('query_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('embed_session_id', sa.Uuid(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('analysis_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lease_id', sa.Uuid(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id', 'operation', 'idempotency_key')
    )
    op.create_index(op.f('ix_integrationtask_client_id'), 'integrationtask', ['client_id'], unique=False)
    op.create_index(op.f('ix_integrationtask_conversation_id'), 'integrationtask', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_integrationtask_identity_id'), 'integrationtask', ['identity_id'], unique=False)
    op.create_index(op.f('ix_integrationtask_status'), 'integrationtask', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrationtask_status'), table_name='integrationtask')
    op.drop_index(op.f('ix_integrationtask_identity_id'), table_name='integrationtask')
    op.drop_index(op.f('ix_integrationtask_conversation_id'), table_name='integrationtask')
    op.drop_index(op.f('ix_integrationtask_client_id'), table_name='integrationtask')
    op.drop_table('integrationtask')
    op.drop_index(op.f('ix_integrationidentity_client_id'), table_name='integrationidentity')
    op.drop_index(op.f('ix_integrationidentity_actor_id'), table_name='integrationidentity')
    op.drop_table('integrationidentity')
    op.drop_table('integrationclient')
    op.drop_index(op.f('ix_integrationaudit_client_id'), table_name='integrationaudit')
    op.drop_index(op.f('ix_integrationaudit_action'), table_name='integrationaudit')
    op.drop_table('integrationaudit')
    op.drop_table('embedticket')
    op.drop_index(op.f('ix_embedsession_identity_id'), table_name='embedsession')
    op.drop_table('embedsession')
    op.drop_table('assertionuse')
    # ### end Alembic commands ###
