"""add query execution and policies

Revision ID: 5b2dafec4844
Revises: da03a1980203
Create Date: 2026-09-04 15:56:24.542579

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5b2dafec4844'
down_revision = 'da03a1980203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queryevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queryevent_job_id'), 'queryevent', ['job_id'], unique=False)
    op.create_index(op.f('ix_queryevent_topic_id'), 'queryevent', ['topic_id'], unique=False)
    op.create_table('querygate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(sa.text('INSERT INTO querygate (id) VALUES (1)'))
    op.create_table('queryjob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('semantic_version', sa.Integer(), nullable=False),
    sa.Column('policy_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('plan_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('sql_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('result_bytes', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'request_id')
    )
    op.create_index(op.f('ix_queryjob_actor_id'), 'queryjob', ['actor_id'], unique=False)
    op.create_index(op.f('ix_queryjob_source_id'), 'queryjob', ['source_id'], unique=False)
    op.create_index(op.f('ix_queryjob_status'), 'queryjob', ['status'], unique=False)
    op.create_index(op.f('ix_queryjob_topic_id'), 'queryjob', ['topic_id'], unique=False)
    op.create_table('querypolicy',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('grants', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('querypolicy')
    op.drop_index(op.f('ix_queryjob_topic_id'), table_name='queryjob')
    op.drop_index(op.f('ix_queryjob_status'), table_name='queryjob')
    op.drop_index(op.f('ix_queryjob_source_id'), table_name='queryjob')
    op.drop_index(op.f('ix_queryjob_actor_id'), table_name='queryjob')
    op.drop_table('queryjob')
    op.drop_table('querygate')
    op.drop_index(op.f('ix_queryevent_topic_id'), table_name='queryevent')
    op.drop_index(op.f('ix_queryevent_job_id'), table_name='queryevent')
    op.drop_table('queryevent')
    # ### end Alembic commands ###
