const { chromium } = require('@playwright/test')
const fs = require('node:fs')
const path = require('node:path')

async function main() {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } })
  globalThis.inspectionPage = page
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('http://127.0.0.1:8000/login')
  await page.getByTestId('email-input').fill('admin@lightsql.example.com')
  await page.getByTestId('password-input').fill('LightSQL-Demo-2026!')
  await page.getByRole('button', { name: '登录工作空间' }).click()
  await page.waitForURL(/\/topics\/?$/)
  await page.getByRole('link', { name: '查询验证' }).click()
  await page.getByLabel('业务主题', { exact: true }).selectOption('7d5c849d-6148-4140-ae23-fa70c2fc847b')
  await page.getByLabel('销售总额', { exact: true }).uncheck()
  await page.getByLabel('净销售额', { exact: true }).check()
  await page.getByLabel('支付订单数', { exact: true }).check()
  await page.getByLabel('客单价', { exact: true }).check()
  await page.getByLabel('按客户区域分组', { exact: true }).check()
  await page.getByLabel('排序字段', { exact: true }).selectOption('net_sales')
  await page.getByRole('button', { name: '校验并预览', exact: true }).click()
  await page.getByText('校验通过', { exact: false }).waitFor()
  await page.getByText('参数化 SQL（管理员）', { exact: true }).click()
  await page.getByRole('button', { name: '执行查询', exact: true }).click()
  await page.getByRole('cell', { name: '1700.00', exact: true }).waitFor({ timeout: 30000 })
  await page.getByRole('cell', { name: '1200.00', exact: true }).waitFor()
  await page.getByRole('cell', { name: '1100.00', exact: true }).waitFor()
  const target = path.join(__dirname, '../.local/module4-query-page.png')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: target, fullPage: true })
  await page.getByRole('button', { name: '管理查询授权', exact: true }).click()
  const memberOption = page.getByLabel('查询授权成员').locator('option').filter({ hasText: '已配置' }).first()
  await memberOption.waitFor({ state: 'attached' })
  await page.getByLabel('查询授权成员').selectOption(await memberOption.getAttribute('value'))
  await page.getByLabel('授权值', { exact: true }).waitFor()
  if (await page.getByLabel('授权值', { exact: true }).inputValue() !== '1') throw Error('Unexpected tenant grant')
  await page.getByRole('button', { name: '收起查询授权', exact: true }).click()
  await page.getByLabel('结果行数').fill('1')
  await page.getByRole('button', { name: '执行查询', exact: true }).click()
  await page.getByText('已达到结果上限', { exact: false }).waitFor({ timeout: 30000 })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: path.join(__dirname, '../.local/module4-mobile.png'), fullPage: true })
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
  if (overflow) throw Error('Page overflows mobile viewport')
  const analyst = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  analyst.on('pageerror', e => errors.push(e.message))
  await analyst.goto('http://127.0.0.1:8000/login')
  await analyst.getByTestId('email-input').fill('analyst@lightsql.example.com')
  await analyst.getByTestId('password-input').fill('LightSQL-Demo-2026!')
  await analyst.getByRole('button', { name: '登录工作空间' }).click()
  await analyst.waitForURL(/\/topics\/?$/)
  await analyst.getByRole('link', { name: '查询验证' }).click()
  await analyst.getByLabel('销售总额', { exact: true }).uncheck()
  await analyst.getByLabel('净销售额', { exact: true }).check()
  await analyst.getByLabel('按客户区域分组', { exact: true }).check()
  await analyst.getByRole('button', { name: '执行查询', exact: true }).click()
  await analyst.getByRole('cell', { name: '1700.00', exact: true }).waitFor({ timeout: 30000 })
  if (await analyst.getByRole('cell', { name: '华北', exact: true }).count()) throw Error('Tenant isolation failed')
  if (await analyst.getByText('查看执行 SQL', { exact: true }).count()) throw Error('SQL leaked to analyst')
  await analyst.evaluate(() => window.scrollTo(0, 0))
  await analyst.screenshot({ path: path.join(__dirname, '../.local/module4-analyst.png'), fullPage: true })
  if (errors.length) throw Error(errors.join('\n'))
  fs.writeFileSync(path.join(__dirname, '../.local/module4-browser.json'), JSON.stringify({ adminQuery: true, grantVisible: true, truncation: true, mobileOverflow: false, analystIsolation: true, consoleErrors: errors }, null, 2))
  console.log('Browser acceptance passed: query, SQL preview, tenant policy, truncation, mobile layout and analyst isolation.')
  await browser.close()
}
main().catch(async e => { if (globalThis.inspectionPage) { console.log('URL:', globalThis.inspectionPage.url()); console.log((await globalThis.inspectionPage.locator('body').innerText()).slice(-2500)); await globalThis.inspectionPage.screenshot({ path: path.join(__dirname, '../.local/module4-browser-error.png'), fullPage: true }) } console.error(e); process.exit(1) })
