const { chromium, expect } = require('@playwright/test')
const fs = require('node:fs')
const path = require('node:path')
const local = path.join(__dirname, '../.local')
const fixture = JSON.parse(fs.readFileSync(path.join(local, 'module5-fixture.json'), 'utf8'))

async function login(page, email) {
  await page.goto(`${fixture.url}/login`)
  await page.getByTestId('email-input').fill(email)
  await page.getByTestId('password-input').fill('LightSQL-Demo-2026!')
  await page.getByRole('button', { name: '登录工作空间' }).click()
  await page.waitForURL(/\/topics\/?$/)
}

async function ask(page, text) {
  await page.getByLabel('你的业务问题', { exact: true }).or(page.getByLabel('继续追问或补充条件', { exact: true })).fill(text)
  const response = page.waitForResponse(r => r.url().endsWith('/turns') && r.request().method() === 'POST')
  await page.getByRole('button', { name: '发送问题', exact: true }).click()
  if (!(await response).ok()) throw Error('Ask request failed')
  await expect(page.locator('article').last()).toContainText(text)
  await expect(page.locator('article').last()).not.toContainText('正在生成查询计划', { timeout: 15000 })
}

async function main() {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } })
  globalThis.page = page
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await login(page, 'admin@lightsql.example.com')
  await page.getByRole('link', { name: '模型设置', exact: true }).click()
  for (const provider of ['zhipu', 'deepseek', 'qwen']) {
    await page.getByRole('button', { name: '添加模型配置', exact: true }).click()
    await page.getByLabel('配置名称', { exact: true }).fill(`${provider} 协议测试`)
    await page.getByLabel('模型厂商', { exact: true }).selectOption(provider)
    await page.getByLabel('模型名称', { exact: true }).fill('fixture-model')
    await page.getByLabel('API Key', { exact: true }).fill('synthetic-key-not-real')
    await page.getByRole('button', { name: '保存配置', exact: true }).click()
    await page.getByRole('heading', { name: `${provider} 协议测试` }).waitFor()
  }
  const qwen = page.locator('section').filter({ has: page.getByRole('heading', { name: 'qwen 协议测试', exact: true }) })
  await qwen.getByRole('button', { name: '测试连接', exact: true }).click()
  await page.getByText('连接与 JSON 输出测试通过', { exact: false }).waitFor()
  await qwen.getByRole('button', { name: '启用此配置', exact: true }).click()
  await expect(qwen).toContainText('当前启用')
  await qwen.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(page.getByLabel('API Key', { exact: true })).toHaveValue('')
  await page.getByLabel('模型名称', { exact: true }).fill('fixture-model-v2')
  await page.getByRole('button', { name: '保存配置', exact: true }).click()
  await expect(qwen).toContainText('fixture-model-v2')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: path.join(local, 'module5-models.png'), fullPage: true })
  await page.getByRole('link', { name: '智能问答', exact: true }).click()
  await page.getByLabel('业务主题', { exact: true }).selectOption(fixture.topic_id)
  await page.getByRole('button', { name: '新建会话', exact: true }).click()
  await page.getByLabel('问答方式', { exact: true }).selectOption('metrics')
  await page.getByLabel('校验通过后自动查询', { exact: true }).uncheck()
  await ask(page, '本月净销售额按客户区域分组')
  await expect(page.locator('article').last()).toContainText('待核对计划')
  await page.getByRole('button', { name: '核对无误，执行查询', exact: true }).click()
  for (const amount of ['1700.00', '1200.00', '1100.00']) await page.getByRole('cell', { name: amount, exact: true }).waitFor({ timeout: 45000 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: path.join(local, 'module5-answer.png'), fullPage: true })
  await ask(page, '只看官网')
  await expect(page.locator('article').last()).toContainText('online')
  await expect(page.locator('article').last()).toContainText('客户区域')
  await page.getByRole('button', { name: '核对无误，执行查询', exact: true }).click()
  await page.locator('article').last().getByRole('cell', { name: '1100.00', exact: true }).waitFor({ timeout: 45000 })
  await ask(page, '清除过滤条件')
  await expect(page.locator('article').last()).toContainText('附加过滤：无')
  await page.getByLabel('清除上下文，独立提问').check()
  await ask(page, '示例渠道净销售额')
  await page.getByLabel('实体选择 示例渠道').selectOption('channel_online')
  await page.getByRole('button', { name: '确认实体并继续', exact: true }).click()
  await expect(page.locator('article').last()).toContainText('待核对计划')
  await ask(page, '张三的净销售额')
  await expect(page.locator('article').last()).toContainText('待核对计划')
  await page.getByLabel('清除上下文，独立提问').check()
  await ask(page, '净销售额同比')
  await expect(page.locator('article').last()).toContainText('暂不支持')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: path.join(local, 'module5-mobile.png'), fullPage: true })
  if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw Error('Mobile page overflow')
  const analyst = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  analyst.on('pageerror', error => errors.push(error.message))
  await login(analyst, 'analyst@lightsql.example.com')
  await expect(analyst.getByRole('link', { name: '模型设置', exact: true })).toHaveCount(0)
  await analyst.getByRole('link', { name: '智能问答', exact: true }).click()
  await analyst.getByLabel('业务主题', { exact: true }).selectOption(fixture.topic_id)
  await analyst.getByRole('button', { name: '新建会话', exact: true }).click()
  await analyst.getByLabel('问答方式', { exact: true }).selectOption('metrics')
  await analyst.getByLabel('校验通过后自动查询', { exact: true }).uncheck()
  await ask(analyst, '净销售额按客户区域分组')
  await analyst.getByRole('button', { name: '核对无误，执行查询', exact: true }).click()
  await analyst.getByRole('cell', { name: '1700.00', exact: true }).waitFor({ timeout: 45000 })
  await analyst.getByRole('cell', { name: '1100.00', exact: true }).waitFor()
  await expect(analyst.getByRole('cell', { name: '华北', exact: true })).toHaveCount(0)
  await expect(analyst.getByText('查看执行 SQL', { exact: true })).toHaveCount(0)
  await analyst.evaluate(() => window.scrollTo(0, 0))
  await analyst.screenshot({ path: path.join(local, 'module5-analyst.png'), fullPage: true })
  if (errors.length) throw Error(errors.join('\n'))
  fs.writeFileSync(path.join(local, 'module5-browser.json'), JSON.stringify({ modelMode: 'local protocol replay, NOT live LLM', realSource: 'PostgreSQL synthetic data', providersConfigured: ['zhipu', 'deepseek', 'qwen'], keyNotEchoed: true, switch: true, adminAmount: '4000.00', analystAmount: '2800.00', followup: true, clearFilters: true, ambiguity: true, naturalLanguageAccepted: true, unsupported: true, mobileOverflow: false, scriptErrors: errors }, null, 2))
  console.log('M05 browser acceptance passed using explicitly isolated model protocol replay.')
  await browser.close()
}
main().catch(async error => { console.error(error); if (globalThis.page) { console.log((await globalThis.page.locator('body').innerText()).slice(-2000)); await globalThis.page.screenshot({ path: path.join(local, 'module5-browser-error.png'), fullPage: true }) } process.exit(1) })
