// Isolated M07 acceptance: persisted reviews, real source results, explicit replay.
const { chromium, expect } = require('@playwright/test')
const fs = require('node:fs')
const path = require('node:path')
const { execFileSync } = require('node:child_process')
const root = path.resolve(__dirname, '..')
const local = path.join(root, '.local')
const fixture = JSON.parse(fs.readFileSync(path.join(local, 'module5-fixture.json'), 'utf8'))
const stamp = Date.now()

async function main() {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } })
    const page = await context.newPage()
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto(fixture.url + '/login')
    await page.getByTestId('email-input').fill('admin@lightsql.example.com')
    await page.getByTestId('password-input').fill('LightSQL-Demo-2026!')
    await page.getByRole('button', { name: '登录工作空间' }).click()
    await page.waitForURL(/\/topics\/?$/)
    const login = await context.request.post(fixture.url + '/api/v1/login/access-token', { form: { username: 'admin@lightsql.example.com', password: 'LightSQL-Demo-2026!' } })
    const token = (await login.json()).access_token
    const headers = { Authorization: 'Bearer ' + token }
    const topic = await (await context.request.get(fixture.url + '/api/v1/topics/' + fixture.topic_id, { headers })).json()
    const gold = JSON.parse(fs.readFileSync(path.join(root, 'docs/examples/M07合成冒烟题集.json'), 'utf8'))
    gold.topic_id = fixture.topic_id
    gold.semantic_version = topic.current_version
    const goldPath = path.join(local, `module7-gold-${stamp}.json`)
    fs.writeFileSync(goldPath, JSON.stringify(gold))
    await page.goto(fixture.url + '/quality')
    await expect(page.getByRole('heading', { name: '需要关注' })).toBeVisible()
    await page.screenshot({ path: path.join(local, 'module7-operations.png'), fullPage: true })
    await page.getByRole('button', { name: '质量评测', exact: true }).click()
    await page.getByLabel('导入金标题集 JSON').setInputFiles(goldPath)
    await expect(page.getByLabel('比较题集')).not.toHaveValue('')
    const datasetId = await page.getByLabel('比较题集').inputValue()
    const dataset = await (await context.request.get(fixture.url + '/api/v1/quality/datasets/' + datasetId, { headers })).json()
    const exportPath = path.join(local, `module7-export-${stamp}.json`)
    fs.writeFileSync(exportPath, JSON.stringify(dataset))
    const summaries = []
    for (const split of ['dev', 'blind']) {
      const reportPath = path.join(local, `module7-${split}-${stamp}.json`)
      execFileSync(path.join(root, '.venv/Scripts/python.exe'), [path.join(root, 'scripts/evaluate_questions.py'), exportPath, '--url', fixture.url, '--output', reportPath, '--split', split, '--evidence', 'protocol_replay'], { cwd: root, env: { ...process.env, LIGHTSQL_EVAL_TOKEN: token }, stdio: ['ignore', 'pipe', 'pipe'], timeout: 180000 })
      await page.getByLabel('导入评测运行 JSON').setInputFiles(reportPath)
      await page.getByLabel('评测集合').selectOption(split)
      await expect(page.getByText('协议回放 · 非质量结论', { exact: false })).toBeVisible()
      const runs = await (await context.request.get(fixture.url + '/api/v1/quality/runs?dataset_id=' + datasetId, { headers })).json()
      const run = runs.find(r => r.split === split)
      if (!run || run.summary.correct !== run.summary.total) throw Error('Replay source results did not match independent reference gold')
      summaries.push({ split, summary: run.summary })
    }
    await page.getByLabel('评测集合').selectOption('dev')
    await page.screenshot({ path: path.join(local, 'module7-evaluation.png'), fullPage: true })
    const history = await (await context.request.get(fixture.url + '/api/v1/assistant/conversations', { headers })).json()
    const conversation = history.find(c => c.turns.some(t => t.question === '查询净销售额'))
    const turn = conversation.turns[0]
    const feedback = await context.request.put(fixture.url + `/api/v1/assistant/conversations/${conversation.id}/turns/${turn.id}/feedback`, { headers, data: { rating: 'incorrect', category: 'metric', comment: 'M07浏览器回归：核对合成净额口径' } })
    if (!feedback.ok()) throw Error('Feedback failed')
    await page.getByRole('button', { name: '反馈审核', exact: true }).click()
    const card = page.locator('article').filter({ hasText: 'M07浏览器回归' })
    await expect(card).toBeVisible()
    await card.getByLabel('审核结论').selectOption('resolved')
    await card.getByLabel('关联题集').selectOption(datasetId)
    await card.getByLabel('回归题').selectOption('net-total')
    await card.getByLabel('审核说明').fill('独立参考 SQL 核对为 4000 元，已关联回归题。')
    await card.getByRole('button', { name: '保存审核' }).click()
    await expect(card).toContainText('已解决 · v2')
    await page.reload()
    await page.getByRole('button', { name: '反馈审核', exact: true }).click()
    await expect(page.locator('article').filter({ hasText: 'M07浏览器回归' })).toContainText('已解决 · v2')
    await page.screenshot({ path: path.join(local, 'module7-feedback.png'), fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.getByRole('button', { name: '质量评测', exact: true }).click()
    await page.getByLabel('比较题集').selectOption(datasetId)
    await expect(page.getByText('协议回放 · 非质量结论', { exact: false })).toBeVisible()
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)
    if (overflow) throw Error('Mobile page overflow')
    await page.screenshot({ path: path.join(local, 'module7-mobile.png'), fullPage: true })
    if (errors.length) throw Error(JSON.stringify(errors))
    fs.writeFileSync(path.join(local, 'module7-browser.json'), JSON.stringify({ datasetId, summaries, browser_errors: errors, mobile_overflow: overflow, reviewed: true }, null, 2))
    console.log(JSON.stringify({ cases: summaries.reduce((n, r) => n + r.summary.total, 0), reviewed: true, browser_errors: errors.length, mobile_overflow: overflow }))
  } finally { await browser.close() }
}
main().catch(error => { console.error(error.message); process.exit(1) })
